# Generated by Django 5.2.8 on 2026-04-18 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0003_alter_ambiente_table'),
        ('patrimonios', '0003_rename_current_ambiente_id_patrimonio_current_ambiente'),
        ('sensores', '0002_alter_sensor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_saida', to='ambientes.ambiente')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='patrimonios.patrimonio')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sensores.sensor')),
                ('to_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_entrada', to='ambientes.ambiente')),
            ],
            options={
                'db_table': 'movement_log',
            },
        ),
    ]
