// Mock data for the RFID Asset Management System
import { Environment, Asset, Sensor, MovementLog } from '../types';

export const mockEnvironments: Environment[] = [
  {
    id: 'env-1',
    name: 'Sala TI',
    description: 'Sala de Tecnologia da Informação',
    createdAt: new Date('2025-01-15'),
  },
  {
    id: 'env-2',
    name: 'Almoxarifado',
    description: 'Depósito de materiais',
    createdAt: new Date('2025-01-15'),
  },
  {
    id: 'env-3',
    name: 'Recepção',
    description: 'Área de recepção',
    createdAt: new Date('2025-01-15'),
  },
  {
    id: 'env-4',
    name: 'Sala de Reuniões',
    description: 'Sala para reuniões',
    createdAt: new Date('2025-01-16'),
  },
  {
    id: 'env-5',
    name: 'Laboratório',
    description: 'Laboratório de testes',
    createdAt: new Date('2025-01-16'),
  },
];

export const mockAssets: Asset[] = [
  {
    id: 'asset-1',
    epc: 'E200001A75020108',
    name: 'Notebook Dell Latitude',
    description: 'Notebook corporativo',
    currentEnvironmentId: 'env-1',
    lastReadAt: new Date('2025-10-26T10:30:00'),
    createdAt: new Date('2025-01-20'),
  },
  {
    id: 'asset-2',
    epc: 'E200001A75020109',
    name: 'Monitor LG 27"',
    description: 'Monitor LED',
    currentEnvironmentId: 'env-1',
    lastReadAt: new Date('2025-10-26T09:15:00'),
    createdAt: new Date('2025-01-20'),
  },
  {
    id: 'asset-3',
    epc: 'E200001A75020110',
    name: 'Projetor Epson',
    description: 'Projetor portátil',
    currentEnvironmentId: 'env-4',
    lastReadAt: new Date('2025-10-26T11:20:00'),
    createdAt: new Date('2025-01-21'),
  },
  {
    id: 'asset-4',
    epc: 'E200001A75020111',
    name: 'Impressora HP LaserJet',
    description: 'Impressora laser',
    currentEnvironmentId: 'env-2',
    lastReadAt: new Date('2025-10-26T08:45:00'),
    createdAt: new Date('2025-01-21'),
  },
  {
    id: 'asset-5',
    epc: 'E200001A75020112',
    name: 'Roteador Cisco',
    description: 'Roteador corporativo',
    currentEnvironmentId: 'env-1',
    lastReadAt: new Date('2025-10-25T16:30:00'),
    createdAt: new Date('2025-01-22'),
  },
  {
    id: 'asset-6',
    epc: 'E200001A75020113',
    name: 'Tablet Samsung',
    description: 'Tablet industrial',
    currentEnvironmentId: 'env-3',
    lastReadAt: new Date('2025-10-26T10:00:00'),
    createdAt: new Date('2025-01-22'),
  },
  {
    id: 'asset-7',
    epc: 'E200001A75020114',
    name: 'Scanner de Código de Barras',
    description: 'Scanner portátil',
    currentEnvironmentId: 'env-2',
    lastReadAt: new Date('2025-10-26T09:30:00'),
    createdAt: new Date('2025-01-23'),
  },
  {
    id: 'asset-8',
    epc: 'E200001A75020115',
    name: 'Câmera de Segurança',
    description: 'Câmera IP',
    currentEnvironmentId: 'env-5',
    lastReadAt: new Date('2025-10-26T07:15:00'),
    createdAt: new Date('2025-01-23'),
  },
];

export const mockSensors: Sensor[] = [
  {
    id: 'sensor-1',
    name: 'Sensor TI -> Almoxarifado',
    exitEnvironmentId: 'env-1',
    entryEnvironmentId: 'env-2',
    isActive: true,
    createdAt: new Date('2025-01-18'),
  },
  {
    id: 'sensor-2',
    name: 'Sensor Recepção -> Sala TI',
    exitEnvironmentId: 'env-3',
    entryEnvironmentId: 'env-1',
    isActive: true,
    createdAt: new Date('2025-01-18'),
  },
  {
    id: 'sensor-3',
    name: 'Sensor Sala Reuniões -> Recepção',
    exitEnvironmentId: 'env-4',
    entryEnvironmentId: 'env-3',
    isActive: true,
    createdAt: new Date('2025-01-19'),
  },
  {
    id: 'sensor-4',
    name: 'Sensor Almoxarifado -> Laboratório',
    exitEnvironmentId: 'env-2',
    entryEnvironmentId: 'env-5',
    isActive: true,
    createdAt: new Date('2025-01-19'),
  },
  {
    id: 'sensor-5',
    name: 'Sensor Laboratório -> Sala TI',
    exitEnvironmentId: 'env-5',
    entryEnvironmentId: 'env-1',
    isActive: false,
    createdAt: new Date('2025-01-20'),
  },
];

export const mockMovementLogs: MovementLog[] = [
  {
    id: 'log-1',
    assetId: 'asset-1',
    sensorId: 'sensor-2',
    fromEnvironmentId: 'env-3',
    toEnvironmentId: 'env-1',
    timestamp: new Date('2025-10-26T10:30:00'),
    status: 'valid',
  },
  {
    id: 'log-2',
    assetId: 'asset-3',
    sensorId: 'sensor-3',
    fromEnvironmentId: 'env-4',
    toEnvironmentId: 'env-3',
    timestamp: new Date('2025-10-26T11:20:00'),
    status: 'valid',
  },
  {
    id: 'log-3',
    assetId: 'asset-6',
    sensorId: 'sensor-2',
    fromEnvironmentId: 'env-3',
    toEnvironmentId: 'env-1',
    timestamp: new Date('2025-10-26T10:00:00'),
    status: 'suspicious',
  },
  {
    id: 'log-4',
    assetId: 'asset-2',
    sensorId: 'sensor-2',
    fromEnvironmentId: 'env-3',
    toEnvironmentId: 'env-1',
    timestamp: new Date('2025-10-26T09:15:00'),
    status: 'valid',
  },
  {
    id: 'log-5',
    assetId: 'asset-7',
    sensorId: 'sensor-1',
    fromEnvironmentId: 'env-1',
    toEnvironmentId: 'env-2',
    timestamp: new Date('2025-10-26T09:30:00'),
    status: 'valid',
  },
  {
    id: 'log-6',
    assetId: 'asset-4',
    sensorId: 'sensor-4',
    fromEnvironmentId: 'env-2',
    toEnvironmentId: 'env-5',
    timestamp: new Date('2025-10-26T08:45:00'),
    status: 'valid',
  },
  {
    id: 'log-7',
    assetId: 'asset-8',
    sensorId: 'sensor-4',
    fromEnvironmentId: 'env-2',
    toEnvironmentId: 'env-5',
    timestamp: new Date('2025-10-26T07:15:00'),
    status: 'valid',
  },
  {
    id: 'log-8',
    assetId: 'asset-5',
    sensorId: 'sensor-2',
    fromEnvironmentId: 'env-3',
    toEnvironmentId: 'env-1',
    timestamp: new Date('2025-10-25T16:30:00'),
    status: 'valid',
  },
  {
    id: 'log-9',
    assetId: 'asset-1',
    sensorId: 'sensor-1',
    fromEnvironmentId: 'env-1',
    toEnvironmentId: 'env-2',
    timestamp: new Date('2025-10-25T14:20:00'),
    status: 'valid',
  },
  {
    id: 'log-10',
    assetId: 'asset-3',
    sensorId: 'sensor-3',
    fromEnvironmentId: 'env-4',
    toEnvironmentId: 'env-3',
    timestamp: new Date('2025-10-25T11:10:00'),
    status: 'valid',
  },
];
