# Generated by Django 5.2.8 on 2025-12-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
