# Generated by Django 5.2.8 on 2026-01-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0002_ambiente_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ambiente',
            table='ambientes',
        ),
    ]
