# Generated by Django 5.2.8 on 2026-01-21 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0002_ambiente_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entry_to_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores_entrada', to='ambientes.ambiente')),
                ('exit_to_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores_saida', to='ambientes.ambiente')),
            ],
        ),
    ]
