# Generated by Django 5.2.8 on 2025-11-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('current_ambiente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientes.ambiente')),
            ],
        ),
    ]
