# Generated by Django 5.2.8 on 2026-01-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patrimonio',
            table='patrimonio',
        ),
    ]
