# Generated by Django 5.2.8 on 2026-01-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0002_alter_patrimonio_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patrimonio',
            old_name='current_ambiente_id',
            new_name='current_ambiente',
        ),
    ]
